version: '3'

services:
  minio:
    restart: always
    image: minio/minio
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: minio_ac
      MINIO_ROOT_PASSWORD: minio_sc
    command: server /data --console-address ":9001"
    volumes:
      - 'minio_data:/data'

volumes:
  minio_data:
    driver: local
